In [2]:
import numpy as np


In [2]:
!pip install numpy

In [3]:
a1 = np.array([1,2,3])

In [5]:
a2 = np.array([[1,2,3],[4,5,6]])

In [19]:
type(a1)

numpy.ndarray

In [7]:
print(a1)

[1 2 3]


In [8]:
print(a2)

[[1 2 3]
 [4 5 6]]


In [20]:
#Creating Arrays from Scratch:
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.zeros((3, 3))    # 3x3 array of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2, 4))     # 2x4 array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.full((2, 2), 7)  # 2x2 array filled with 7

array([[7, 7],
       [7, 7]])

In [13]:
np.eye(4)           # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)

array([1, 3, 5, 7, 9])

In [24]:
#array properties
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [25]:
# Changing Data Types
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]


float32
[1 2 3]


In [27]:
# Reshaping and Flattening Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [28]:
#Indexing (Same as Python Lists)
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [29]:
#Slicing (Extracting Parts of an Array)
arr = np.array([10, 20, 30, 40, 50])
 
print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [30]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40  50]


In [3]:
#Fancy Indexing (Select Multiple Elements)
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [4]:
#Boolean Masking (Filter Data)
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]
