In [2]:
#Create a 3×3 array filled with random numbers and print its shape.
import numpy as np
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr)

(3, 3)

In [9]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
arr = np.array([1.1,2.2,3.3] ,dtype = np.int32)
print(arr)

[1 2 3]


In [13]:
arr = np.array([1.1,2.2,3.3])
print(arr.dtype)

float64


In [15]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr = np.array([1,2,3,4,5,6])
idx = [0,1,2]
print(arr[idx])


[1 2 3]


In [1]:
import numpy as np
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr = np.array([1, 2, 3, 4, 5, 6])

# indices of even numbers (2, 4, 6)
idx = [1, 3, 5]

even_numbers = arr[idx]
print(even_numbers)

[2 4 6]


In [13]:
#Reshape a 1D array of size 9 into a 3×3 matrix.
arr = np.array([1,2,3,4,5,6,7,8,9])
print("shape:",arr.shape)
print("size:",arr.size)
reshape = arr.reshape(3,3)
print(reshape)

shape: (9,)
size: 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("size:",arr.size)

shape: (2, 3)
size: 6


In [18]:
#Use boolean masking to filter numbers greater than 50 in an array.
arr = np.array([20,40,60,80])
mask = arr>50
print(mask)
print(arr[mask])

[False False  True  True]
[60 80]


In [22]:
#Summary (Exam Ready)
# Multidimensional Indexing
# arr[row, column]
# : means all elements
# Used to access/slice 2D or higher arrays
# 🔹 Axis
# axis=0 → operate down rows (column-wise)
# axis=1 → operate across columns (row-wise)
#Example 2D Array

import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr[0, 1]   # row 0, column 1    # acessing single element



np.int64(2)

In [23]:
arr[0]   # first row   #Access full row

array([1, 2, 3])

In [24]:
arr[:, 1]   # all rows, column 1 full col acessing

array([2, 5])

In [25]:
arr[0:2, 1:3] #slicing

array([[2, 3],
       [5, 6]])

In [26]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
np.sum(arr, axis=0) #Sum along Axis 0 (column-wise)

array([5, 7, 9])

In [27]:
np.sum(arr, axis=1) #Sum along Axis 1 (row-wise)

array([ 6, 15])

In [28]:
#3D array
# Dimensions Meaning:
# 1st index → Layer (depth)
# 2nd index → Row
# 3rd index → Column
# Colon : Meaning: Select all elements in that dimension

import numpy as np
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])
arr[0, 1, 2] #Access single element

np.int64(6)

In [29]:
#Access entire layer
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
#Access specific row from a layer
arr[0,1]

array([4, 5, 6])

In [31]:
arr[1,0]

array([7, 8, 9])

In [32]:
#Access specific column across all layers
arr[:, :, 1]

array([[ 2,  5],
       [ 8, 11]])

In [33]:
#Slicing in 3D
arr[:, 0:2, 1:3]

array([[[ 2,  3],
        [ 5,  6]],

       [[ 8,  9],
        [11, 12]]])

In [2]:
#vectoragation
import numpy as np

arr = np.array([1, 2, 3, 4])

result = arr * 2
print(result)

[2 4 6 8]


In [3]:
#broadcasting
arr = np.array([1, 2, 3, 4])

result = arr * 2
print(result+10)


[12 14 16 18]


In [4]:
arr = np.array([1, 2, 3])

print(arr ** 2)

[1 4 9]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])
np.add(arr, 2)        # [3 4 5 6]
np.subtract(arr, 1)   # [0 1 2 3]
np.multiply(arr, 2)   # [2 4 6 8]
np.divide(arr, 2)     # [0.5 1. 1.5 2.]

array([0.5, 1. , 1.5, 2. ])

In [8]:
np.subtract(arr, 1)   # [0 1 2 3]

array([0, 1, 2, 3])

In [9]:
np.multiply(arr, 2)   # [2 4 6 8]

array([2, 4, 6, 8])

In [10]:
np.divide(arr, 2)     # [0.5 1. 1.5 2.]

array([0.5, 1. , 1.5, 2. ])

In [12]:
np.power(arr, 2)   # [1 4 9 16]
np.sqrt(arr)       # square root
np.cbrt(arr)       # cube root

array([1.        , 1.25992105, 1.44224957, 1.58740105])

In [13]:
np.exp(arr)        # e^x
np.log(arr)        # natural log (ln)
np.log10(arr)      # base 10 log
np.log2(arr)       # base 2 log

array([0.       , 1.       , 1.5849625, 2.       ])

In [14]:
np.exp(arr)        # e^x

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [15]:
np.sqrt(arr)       # square root

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [16]:
np.sin(arr)
np.cos(arr)
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [17]:
#Find square of all elements using vectorization
arr = np.array([1,2,3])
sq = arr**2
print(sq)


[1 4 9]


In [27]:
#Add two arrays using vectorization
a1 = np.array([1,2,3])
a2 = np.array([4,2,5])
result = a1+a2
print(result)

[5 4 8]


In [25]:
#Add two arrays using vectorization
a1 = np.array([1,2,3])
np.add(a1,2)



array([3, 4, 5])

In [26]:
#Add two arrays using vectorization
a1 = np.array([1,2,3])
a2 = np.array([4,2,5])
result = a1 + a2
print(result)

[5 4 8]


In [28]:
#Use broadcasting to add 10 to all elements
a = np.array([2,3,4])
print(a+10)

[12 13 14]


In [29]:
#Add row-wise using broadcasting
arr = np.array([[1,2,3],
                [4,5,6]])

b = np.array([10,20,30])
print(arr + b)

[[11 22 33]
 [14 25 36]]


In [32]:
#Find sum of each column (axis concept)
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.sum(arr, axis=0)
r1 = np.sum(arr, axis = 1)
print(r1)
print(result)

[ 6 15]
[5 7 9]


In [35]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

arr -2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [36]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.prod(arr, axis=0)
print(result)

[ 4 10 18]


In [37]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.mean(arr, axis=0)
print(result)

[2.5 3.5 4.5]


In [39]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.max(arr, axis=0)
print(result)

[4 5 6]


In [40]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.min(arr, axis=0)
print(result)

[1 2 3]


In [41]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

arr + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [42]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [43]:
arr ** 6

array([[    1,    64,   729],
       [ 4096, 15625, 46656]])

In [46]:
#Find sum of each row
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],[7,8,9]])

result = np.sum(arr, axis=1)
print(result)

[ 6 15 24]


In [47]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.sum(arr, axis=1)
print(result)

[ 6 15]


In [48]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.sum(arr, axis=0)
print(result)

[5 7 9]


In [56]:
#Extract even numbers using boolean indexing
a = np.array([1,2,3,4,5,6,7,8,9,0])
res = a[a % 2==0]
print(res)

[2 4 6 8 0]


In [61]:
#Extract elements greater than 3
a = np.array([1,2,3,4,5,6,7,8,9,0])
res = a[a>3]
print(res)

[4 5 6 7 8 9]


In [62]:
#Extract elements greater than 3
a = np.array([1,2,3,4,5,6,7,8,9,0])
res = a>3
print(res)

[False False False  True  True  True  True  True  True False]


In [64]:
#. 2D Slicing

a = np.array([[1, 2, 3],
                [4, 5, 6]])
a[:1]

array([[1, 2, 3]])

In [65]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
a[0:1]

array([[1, 2, 3]])

In [67]:
a[1:2]

array([[4, 5, 6]])

In [68]:
a[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a[-1:2]

array([[4, 5, 6]])

In [70]:
a[0:-1]

array([[1, 2, 3]])

In [71]:
a[-1:-1]

array([], shape=(0, 3), dtype=int64)

In [72]:
a[0:-2]

array([], shape=(0, 3), dtype=int64)

In [73]:
a[-1:-2]

array([], shape=(0, 3), dtype=int64)

In [74]:
#3D Indexing (important)
a = np.array([[1, 2, 3],
                [4, 5, 6],[7,8,9]])

a[:1:2]

array([[1, 2, 3]])

In [75]:
a[:3:2]

array([[1, 2, 3],
       [7, 8, 9]])

In [76]:
a[1:1:2]

array([], shape=(0, 3), dtype=int64)

In [77]:
a[0:1:2]

array([[1, 2, 3]])

In [78]:
a[:1:3]

array([[1, 2, 3]])

In [79]:
a[:2:2]

array([[1, 2, 3]])

In [80]:
a[:2:3]

array([[1, 2, 3]])

In [81]:
a[1:2:2]

array([[4, 5, 6]])

In [85]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
arr[0, :, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
arr[:, :, 0] += 10
print(arr)

[[[11  2  3]
  [14  5  6]]

 [[17  8  9]
  [20 11 12]]]


In [90]:
arr = np.array([1,2,3,4])
b = arr[0:2]

b[0] = 100
print(arr)

[100   2   3   4]
