In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [3]:
import numpy as np
import pandas as pd

# NumPy (no column names)
arr = np.array([[1, 85], [2, 90]])
print(arr)

# Pandas (with labels)
df = pd.DataFrame(arr, columns=["ID", "Marks"])
print(df)

[[ 1 85]
 [ 2 90]]
   ID  Marks
0   1     85
1   2     90


In [4]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Marks": [80, 90, 85]
}, index=["x", "y", "z"])

# loc (label)
print(df.loc["x"])

# iloc (position)
print(df.iloc[0])

Name      A
Marks    80
Name: x, dtype: object
Name      A
Marks    80
Name: x, dtype: object


In [5]:
# handleing missing values
# ans : Pandas provides functions like fillna() and dropna()
import pandas as pd

df = pd.DataFrame({
    "A": [1, None, 3],
    "B": [4, 5, None]
})

# Fill missing with mean
df_filled = df.fillna(df.mean())

# Drop missing
df_dropped = df.dropna()

print(df_filled)
print(df_dropped)

     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  4.5
     A    B
0  1.0  4.0


In [6]:
# broadcasting in NumPy
# ans : Broadcasting allows operations between arrays of different shapes.
import numpy as np

arr = np.array([1, 2, 3])
result = arr + 5

print(result)   # [6 7 8]

[6 7 8]


In [7]:
# GroupBy in Pandas
# ans : Used to group data and apply aggregation functions.
import pandas as pd

df = pd.DataFrame({
    "Dept": ["IT", "HR", "IT"],
    "Salary": [50000, 40000, 60000]
})

result = df.groupby("Dept")["Salary"].mean()
print(result)

Dept
HR    40000.0
IT    55000.0
Name: Salary, dtype: float64


In [8]:
# Merge vs Concat
# ans : merge() → combine on keys (like SQL join)   concat() → stack data
import pandas as pd

df1 = pd.DataFrame({"ID": [1, 2], "Name": ["A", "B"]})
df2 = pd.DataFrame({"ID": [1, 2], "Marks": [80, 90]})

# Merge
merged = pd.merge(df1, df2, on="ID")

# Concat
concat = pd.concat([df1, df2])

print(merged)
print(concat)

   ID Name  Marks
0   1    A     80
1   2    B     90
   ID Name  Marks
0   1    A    NaN
1   2    B    NaN
0   1  NaN   80.0
1   2  NaN   90.0


In [9]:
# Apply Function
# Ans: Used to apply custom logic to columns.
import pandas as pd

df = pd.DataFrame({"Marks": [30, 50, 80]})

df["Result"] = df["Marks"].apply(lambda x: "Pass" if x > 40 else "Fail")

print(df)

   Marks Result
0     30   Fail
1     50   Pass
2     80   Pass


In [10]:
# Remove Duplicates
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "A"],
    "Marks": [80, 90, 80]
})

df_unique = df.drop_duplicates()
print(df_unique)

  Name  Marks
0    A     80
1    B     90


In [11]:
# Top N Values
import pandas as pd

df = pd.DataFrame({"Marks": [50, 90, 80, 95]})

top3 = df.nlargest(3, "Marks")
print(top3)

   Marks
3     95
1     90
2     80


In [12]:
# Find highest salary per department.
import pandas as pd

df = pd.DataFrame({
    "Dept": ["IT", "HR", "IT"],
    "Salary": [50000, 40000, 60000]
})

result = df.groupby("Dept")["Salary"].max()
print(result)

Dept
HR    40000
IT    60000
Name: Salary, dtype: int64
